### ISSUE TITLE
Screenshot url in appdata is unreachable

### ISSUE THREAD

**Issue by bbhtt** [mousepawmedia/omission#1]
https://github.com/mousepawmedia/omission/blob/d122deed0642fbf00e564ba3b160e356532e715b/share/metainfo/com.mousepawmedia.omission.appdata.xml#L41

This makes the Flathub build fail. I have copied the current screenshot from the Flathub web frontend to the flathub repository but this should be fixed upstream

**Comment by CodeMouse92** [comment]
Fixed. The domain lapsed. I renewed it.
